source :rubygems

gem "sinatra", :require => "sinatra/base"
gem "activerecord"
gem "sinatra-activerecord"
gem "sqlite3"

group :development do
  gem "rake"
end

group :test do
  gem "minitest"
  gem "rack-test", :require => "rack/test"
  gem "turn"
end
