source :rubygems

gem "sinatra",              :require => "sinatra/base"
gem "sinatra-activerecord", :require => "sinatra/activerecord"
gem "sinatra-contrib"

gem "sqlite3"

gem "alphadecimal"

group :development do
  gem "rake"
end

group :test do
  gem "minitest"
  gem "rack-test", :require => "rack/test"
  gem "turn"
end
